### ISSUE TITLE
What is the project's relationship with W3C WoT?

### ISSUE THREAD

**Issue by nikosft** [mozilla-iot/wot#145]
It seems that there are some differences with W3C's WoT description candidate recommendation (https://www.w3.org/TR/wot-thing-description), with most notably being the lack of the "security" vocabulary term, and the use of "link" instead of "forms". 

Is there any plan to catch up with W3C or this is going to be a separate specification?

(P.S. I was planning to submit that in discourse but it seems that there are issues with the login page).

**Comment by benfrancis** [comment]
@nikosft Good question. Mozilla's [Web Thing API](https://iot.mozilla.org/wot/) specification and the W3C WoT Working Group's [Thing Description](https://w3c.github.io/wot-thing-description/) specification were written in parallel and have gradually been converging over time.

Some remaining differences like links vs. forms are intentional and are under ongoing discussions. Mozilla's WebThings Gateway implementation does actually expose security metadata in the thing descriptions it generates, but those metadata are largely pointless in their current form because the thing descriptions themselves are authenticated.

Mozilla are not currently members of the WoT Working Group, but we are members of the Interest Group and are hoping to join the Working Group under its new charter next year and aim to continue to converge the specifications until everyone implements a common standard! We have also recently started a new [Web Thing Protocol Community Group](https://www.w3.org/community/web-thing-protocol/) to standardise the WebSocket sub-protocol and other areas which are not currently covered by the Working Group's specifications.
