### ISSUE TITLE
Open Connectivity Foundation (OCF) / Iotivity

### ISSUE THREAD

**Issue by echo1consulting** [mozilla-iot/wot#40]
Hi, what is the difference between this project and the one that the [Open Connectivity Foundation (OCF)](https://openconnectivity.org/) is doing with [Iotivity](https://www.iotivity.org/)? It seems that data models have been documented [here ](https://oneiota.org/). With these two projects, how should a developer decide which project to pursue for development?

Thank You,

**Comment by benfrancis** [comment]
Hi,

There are several existing Web of Things type standardization efforts including those at the [IETF](https://www.ietf.org/id/draft-keranen-t2trg-rest-iot-04.txt), [W3C](https://www.w3.org/WoT/), [OCF](https://openconnectivity.org/developer/specifications) and [OGC](https://github.com/opengeospatial/sensorthings).

The OCF has quite a mature set of specifications which as I understand it are largely based around a new RESTful application protocol called CoAP. CoAP is like a mini HTTP optimised for resource constrained devices and includes a "NOTIFY" extension which allows messages to be pushed from the server to the client. However, CoAP is not supported directly by web browsers so it's not possible to build web applications on top of this protocol without a bridge from CoAP to HTTP. In contrast, this Web Thing API uses HTTP directly and provides a WebSocket API to allow push type messages. This makes it possible to call the API directly from web applications and makes it easy for web developers to apply their tools and skills to IoT directly.

The W3C has quite a similar Web Thing Description and Scripting API specifications, but this Web Thing API specification has more of a focus on concrete programming interfaces using existing web technologies like JSON, HTTP and WebSockets rather than defining an abstract scripting API and an RDF based data model with heavy usage of semantic web technologies.

The IETF provides some general guidance around using RESTful design in IoT and the OGC is focused on a fairly domain-specific solution.

Our current focus is creating a concrete and pragmatic API for connecting physical devices to the web based on existing proven web technologies, but all of these efforts are valuable and I hope they can converge over time. That may involve specifications merging or building on top of one another (e.g. a shared taxonomy with different encodings or protocol bindings).
