### ISSUE TITLE
Get rid of the concrete Web Thing Types

### ISSUE THREAD

**Issue by coderbyheart** [mozilla-iot/wot#56]
I think that providing [a list of pre-defined Thing types](https://github.com/mozilla-iot/wot/blob/9f6bab9897e9223b61aa4580c8418954eab2e3e9/index.html#L597) is beyond the scope of this standard and it opens up the document to be extended for every imaginable device configuration (e.g. #53).

The section on [how to define a Thing type](https://github.com/mozilla-iot/wot/blob/9f6bab9897e9223b61aa4580c8418954eab2e3e9/index.html#L1111) should be the first one, with some examples.

**Comment by benfrancis** [comment]
The intention here was to provide built-in web thing types for a small set of common devices, so that it is easy to get started without having to refer to external schemas. These types would be part of a default implied context, denoted by a special MIME type like application/td+json.

You can think of it a bit like how HTML has some built in tag names but can be extended through XML namespaces (like SVG and OpenGraph), or using Web Components.

As externally designed schemas like iotschema.org mature, it may be possible to defer to those rather than defining built-in types.

We're also finding that defining web thing types at just the thing level is too inflexible. Through the W3C we are investigating standardising "capabilities" - types of properties, actions and events which can be mixed and matched between devices.

So to address your point, it is not out of scope for the moment, but it may be in future.

**Comment by benfrancis** [comment]
Closed by https://github.com/mozilla-iot/wot/commit/7fe0f9eed4021f09043a74feb274ad2f7465dbe1
