### ISSUE TITLE
Thermostat Web Thing Type

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/wot#61]
We should define a web thing type for thermostats

**Comment by thetwc** [comment]
Really appreciate this. 
I’m currently running Qubino, Secure, Horstmann and virtual thermostats so I’m happy to test.

**Comment by ericschultz** [comment]
What would you need for this? I'd like to get my Nest connected.

**Comment by freaktechnik** [comment]
On the topic of nest, someone seems to be trying to get at least some nest devices connected: https://discourse.mozilla.org/t/nest-oauth-flow/29913

**Comment by jaller94** [comment]
I am strongly in favour of adding additional properties for target values.
Separating actual values from target values ensures a trust in the actual values to become inputs for rules. If the Web Thing would immediately reply with a target temperature, it might trigger unexpected actions in a gateway or be less valuable as an input because of this missing separation.

**Comment by mrstegeman** [comment]
Closed in favor of mozilla-iot/schemas#13
